import { colors } from "./colors";

const fullBleed = {
  position: "relative",
  left: "50%",
  right: "50%",
  width: "100vw",
  marginLeft: "-50vw",
  marginRight: "-50vw",
};

export const styles = {
  hero: {
    ...fullBleed,
    background: "linear-gradient(180deg, #F4F2FA 0%, #EDE8F8 100%)",
    padding: "64px 32px 56px",
    textAlign: "center",
  },
  heroInner: { maxWidth: "700px", margin: "0 auto" },
  badgePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 18px",
    borderRadius: "999px",
    background: "#FFFFFF",
    marginBottom: "24px",
  },
  badgeText: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "12px",
    fontWeight: "800",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: colors.primary,
  },
  heroTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: "40px",
    fontWeight: "900",
    color: "#1F2937",
    marginBottom: "14px",
  },
  heroSubtitle: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    color: "#6B7280",
    fontSize: "15.5px",
  },

  section: {
    maxWidth: "1180px",
    margin: "0 auto",
    padding: "56px 32px",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "360px 1fr",
    gap: "24px",
  },

  infoColumn: { display: "flex", flexDirection: "column", gap: "16px" },
  infoCard: {
    background: "#FFFFFF",
    border: "1px solid #F1F3F5",
    borderRadius: "18px",
    padding: "20px",
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  infoIconWrap: {
    width: "44px",
    height: "44px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
    flexShrink: 0,
  },
  infoLabel: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "12px",
    color: "#9CA3AF",
    marginBottom: "2px",
  },
  infoValue: {
    fontFamily: "'Sora', sans-serif",
    fontSize: "14px",
    fontWeight: "700",
    color: "#1F2937",
  },
  followWrap: { width: "100%" },
  followLabel: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "11px",
    fontWeight: "800",
    letterSpacing: "0.08em",
    color: "#9CA3AF",
    marginBottom: "12px",
  },
  socialRow: { display: "flex", gap: "10px" },
  socialCircle: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    background: "#F3F4F6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    textDecoration: "none",
  },

  formCard: {
    background: "#FFFFFF",
    border: "1px solid #F1F3F5",
    borderRadius: "22px",
    padding: "36px",
  },
  formHeading: {
    fontFamily: "'Sora', sans-serif",
    fontSize: "20px",
    fontWeight: "800",
    color: "#1F2937",
    marginBottom: "24px",
  },
  formRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  formField: { marginBottom: "18px" },
  formLabel: {
    display: "block",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "13px",
    fontWeight: "700",
    color: "#374151",
    marginBottom: "6px",
  },
  formInput: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: "10px",
    border: "1px solid #E5E7EB",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "13.5px",
    outline: "none",
    boxSizing: "border-box",
  },
  formTextarea: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: "10px",
    border: "1px solid #E5E7EB",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "13.5px",
    outline: "none",
    resize: "vertical",
    boxSizing: "border-box",
  },
  formError: {
    color: "#DC2626",
    fontSize: "13px",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    marginBottom: "12px",
  },
  formSuccess: {
    color: "#059669",
    fontSize: "13px",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    marginBottom: "12px",
  },
  submitButton: {
    width: "100%",
    padding: "14px",
    borderRadius: "12px",
    border: "none",
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.blend} 100%)`,
    color: "#FFFFFF",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "14px",
    fontWeight: "700",
    cursor: "pointer",
  },
};